#!/bin/bash


# Sends an alert email if /boot gets too full
# 28.11.2016 - Denis Walther

# Define your hostname:
HOSTNAME="your_hostname"

# Define your mail address:
MAILTO="your_mail_address"

# Check the actual used space on /boot:
SPACE=`df -h /boot | awk '{ print $5 }' | sed -n 2p`

# Loop to check and send mail:
if [ $SPACE > '90%' ] 
  then
    echo "Warning! /boot on $HOSTNAME is almost full. Fix it asap!" | mail -s "/boot on $HOSTNAME almost full" $MAIL
fi



